broadinstitute/cromwhelm

cromwell-helm/Chart.yaml
cromwell-helm/templates/cromwell.yaml

It's not my favorite approach in the world, but I suspect anything fancier than `sed` would be a lot of work to get going.
At least we can flag the sensitive areas as per @cjllanwarne's suggestion.

Comments urging version string format stability [BW-1211]

---

scripts/workspace_cromwell.py

Example usage (assuming cromshell is preinstalled):
```
% python3 scripts/workspace_cromwell.py start                                                                                15:05:43
Scanning for cromshell 2...
Cromshell 2 version detected: 2.0.0
app_name=None; app_status=None
CROMWELL app does not exist. Creating new app with name terra-app-b4acecef-0d69-446d-968d-2b204cc5cbaa
CROMWELL disk not found. Creating new disk with name saturn-pd-b4e549e8-0ead-4c44-aca1-cb0063ebca7d
Waiting for Cromwell app to come up...
Current terra-app-b4acecef-0d69-446d-968d-2b204cc5cbaa status: PROVISIONING...
Current terra-app-b4acecef-0d69-446d-968d-2b204cc5cbaa status: PROVISIONING...
Current terra-app-b4acecef-0d69-446d-968d-2b204cc5cbaa status: PROVISIONING...
Current …
```

BW-1223: `workspace-cromwell` script

---

coa-helm/Chart.yaml
coa-helm/README.md
coa-helm/templates/cromwell-deployment.yaml
coa-helm/templates/csi/blobfuse-proxy.yaml
coa-helm/templates/csi/csi-blob-controller.yaml
coa-helm/templates/csi/csi-blob-driver.yaml
coa-helm/templates/csi/csi-blob-node.yaml
coa-helm/templates/csi/rbac-csi-blob-controller.yaml
coa-helm/templates/csi/rbac-csi-blob-node.yaml
coa-helm/templates/mysqldb-deployment.yaml
coa-helm/templates/persistence.yaml
coa-helm/templates/service.yaml
coa-helm/templates/tes-deployment.yaml
coa-helm/templates/triggerservice-deployment.yaml
coa-helm/values.yaml

I don't think the contents of this chart need to be thoroughly reviewed, this is a starting point from which we can reshape things to look more like the GCP chart and eventually integrate the two. I have deployed this to AKS from my local machine with a few manual steps (Cromwell config file upload, database initialization).

Initial pass at chart for deploying to Azure [BT-603]

---

cromwell-helm/templates/_helpers.tpl
cromwell-helm/templates/batch-analysis-ui-service-account.yaml
cromwell-helm/templates/batch-analysis-ui.yaml
cromwell-helm/values.yaml

I tested the changes by deploying the helm chart to an existing Cromwell app using [these instructions](https://github.com/broadinstitute/cromwhelm/blob/main/cromwell-helm/README.md).
CBAS-UI deployment:
SSH-ing to the pod and curl-ing localhost returned HTML content:
```
% kubectl exec -it hsmzgi-cromwell-rls-batch-analysis-ui-depl-6c9b8f9596-sd8tt -n hsmzgi-cromwell-ns -- /bin/sh
/ $ curl http://localhost:8080
<!doctype html><html lang="en"><head><meta http-equiv="Content-Security-Policy" content="base-uri 'self'; object-src 'none'; script-src 'self' https://fast.appcues.com https://us.jsagent.tcell.insight.rapid7.com
https://cdnjs.cloudflare.com 'nonce-DtPBeCXsxbScxbawE5UAnQ==' 'nonce-ulxxBgzmiZoZLbUqFyrugw=='; style-src * 'unsafe-inline'"><meta charset="utf-8"><meta name="viewport" …
```

BW-1188 Add terra-batch-analysis-ui to helm chart

---

cromwell-helm/templates/_helpers.tpl
cromwell-helm/templates/cbas-deployment.yaml
cromwell-helm/values.yaml

Note: There is no network connectivity to the pod, nor does the pod have a shell to connect to, but logs and uptime seem to indicate that the service is running correctly:
```
[...]
[...]"message":"Tomcat started on port(s): 8080 (http)[...]
[...]
```

BW-1248: Add CBAS deployment to CaaA

---

scripts/workspace_cromwell.py

AoU projects has different prefix (adding vpc-sc).

[RW-8461] Support AoU Google project prefix when checking leo url

---

cromwell-helm/templates/batch-analysis-ui.yaml

Updates the UI image to latest image that contains changes that make the UI proxy aware.
Related terra-batch-analysis-ui PR: https://github.com/DataBiosphere/terra-batch-analysis-ui/pull/2
Closes https://broadworkbench.atlassian.net/browse/BW-1266

BW-1266 Make CBAS UI proxy aware

---

cromwell-helm/templates/cbas-deployment.yaml
cromwell-helm/templates/reverse-proxy-config.yaml

Closes https://broadworkbench.atlassian.net/browse/BW-1284

BW-1284 Move default path in reverse-proxy-config and update CBAS service to latest image

---

coa-helm/values.yaml
cromwell-helm/values.yaml

Closes https://broadworkbench.atlassian.net/browse/BW-1308

BW-1308 Update CBAS and CBAS UI images

---

.github/workflows/make_leo_pr.yml

instead of trying to cut away filename

[WM-1490] extract semantic version directly

---

.github/workflows/automerge.yml

this change will allow us to test the changes needed to the version of this workflow in Leonardo.

[WM-1463] test: require labeler to have login=='broadbot'

---

.github/workflows/broadbot-label.yml

this is a test workflow that needs to be merged to `main`, but will not need to be kept in this repo

[WM-1471] add broadbot-label action

---

test-file.txt

this is a PR into my test workflows branch to see what github events are dumped... because I suspect the documentation I'm looking at online is outdated

[JIRA-1234] test workflows branch to merge

---

.github/workflows/automerge.yml
.github/workflows/jenkins-simulator.yml

there are a few checks that are disabled in this PR, that will be re-enabled in subsequent PRs, and a github action that will be removed after testing is complete

[WM-1556] set up automerge test trigger

---

coa-helm/local_values.template.yaml
coa-helm/templates/cromwell.yaml
coa-helm/values.yaml

Supports https://github.com/broadinstitute/cromwell/pull/6954

WX-697 Support for getting blob SAS token from WSM in Azure

---

test-file

Removing this file to trigger github action

WX-697 Remove test-file

---

terra-batch-libchart/values.yaml

Apparently there is no auto-update for this yet.

WX-697 Update Cromwell version

---

coa-helm/templates/cbas-ui.yaml
cromwell-helm/templates/cbas-ui.yaml

Implementing configuration used in https://github.com/DataBiosphere/cbas-ui/pull/60

WX-862: Add WDS and Cromwell URL configuration to cbas ui

---

terra-batch-libchart/templates/_postgres.tpl
terra-batch-libchart/values.yaml

Removes WDS-specific SQL statements which are no longer needed.
Also removes the /wds-helpers directory entirely from the postgres container.
https://broadinstitute.slack.com/archives/C03T815L316/p1674168134443859

AJ-792: Remove wds seeding

---

terra-batch-libchart/templates/_wds.tpl
terra-batch-libchart/values.yaml

The Sam URL value is dependent on https://github.com/DataBiosphere/leonardo/pull/3114
the MRG value should work as-is

AJ-763: add Sam url and MRG to WDS

---

coa-helm/templates/cbas-api.yaml
coa-helm/templates/cbas-ui.yaml
coa-helm/templates/cromwell.yaml
coa-helm/templates/persistence.yaml
coa-helm/templates/wds.yaml
cromwell-helm/templates/cbas-api.yaml
cromwell-helm/templates/cbas-ui.yaml
cromwell-helm/templates/cromwell.yaml
cromwell-helm/templates/job-manager.yaml
cromwell-helm/templates/wds.yaml
cromwell-helm/values.yaml
terra-batch-libchart/templates/_reverse-proxy.tpl
terra-batch-libchart/values.yaml

https://broadworkbench.atlassian.net/browse/IA-4039
Separate from https://github.com/broadinstitute/cromwhelm/pull/192 to not muddy the waters.
We previously made things disablable for Azure -- doing similar for GCP.

[IA-4039] Make cbas/ui/wds/cromwell disable-able on the GCP side

---

coa-helm/README.md

🤦 One more no-op update to make publish job work

AJ-764 update README again

---

coa-helm/templates/cromwell.yaml

See https://github.com/broadinstitute/cromwell/pull/7103

WX-975 Remove obsolete config

---

README.md

The main purpose of this PR is to make a non-essential change and merge it to Cromwhlem repo so that the Github actions can run successfully and create a Leo PR to update CBAS UI version so that the linked ticket changes can be merged to Dev.
Closes https://broadworkbench.atlassian.net/browse/WM-1856

[WM-1856] Update Readme to add brief info about coa-helm and cromwell-helm chart

---

terra-batch-libchart/values.yaml

https://broadworkbench.atlassian.net/browse/AJ-1005
Just for reliability -- pin Postgres to current working version as of the day of this PR for Terra on Azure

AJ-1005: Pin postgres to 15.2

---

cromwell-helm/templates/persistence.yaml

Found and fixed this error when testing https://github.com/broadinstitute/cromwhelm/pull/265, found it uncommitted in my local env just now 😭

WX-1247 Fix postgres value name

---

coa-helm/templates/cromwell.yaml

See also https://github.com/broadinstitute/terra-helmfile/pull/4782

WX-1337 Include database connectivity in health check
