broadinstitute/cromwhelm

.gitignore
CromwellHsqldbLocalMinikube/Chart.yaml
CromwellHsqldbLocalMinikube/README.md
CromwellHsqldbLocalMinikube/templates/cromwell-service.yaml
CromwellHsqldbLocalMinikube/templates/cromwell.yaml

Taking even more complexity out of the equation, an entirely self-contained Cromwell deployment and no config

Local Cromwell with Hsqlsb [BW-816]

---

cromwell-helm/README.md

Noticed while testing out #24. It turns out `<value>` doesn't display in markdown, so some of the documentation for live refreshing helm charts was not showing up

Fix markdown issues in README [BT-618]

---

.github/workflows/update-and-publish-helm-chart.yml

I tested it on my branch. Details:
- Github action [output #15](https://github.com/broadinstitute/cromwhelm/runs/6103872389?check_suite_focus=true) that updates chart version from 0.1.10 to 0.1.11 (this is because my branch didn't have latest changes from 'main' branch where the version number is 0.2.0)
- Updated `index.yaml` and chart version can be seen in [auto-chart-version-update-0.1.11 branch](https://github.com/broadinstitute/cromwhelm/compare/auto-chart-version-update-0.1.11) created during testing
Closes https://broadworkbench.atlassian.net/browse/BW-1209

[BW-1209] Auto update cromwell-helm chart upon merge to 'main'

---

.github/workflows/update-and-publish-helm-chart.yml

The [Auto update cromwell-helm chart upon merge to 'main'](https://github.com/broadinstitute/cromwhelm/pull/23) missed out on adding the newly created packaged chart to the `charts/` folder. Not sure how I missed this but I had to explicitly to `git add charts/<new-chart>.tgz` to have it pushed to main. I tested out the changes in my branch and have the changes pushed to a new branch.
Previously:
- The auto update publish run after merging PR-23 pushed only the updated `index.yaml` and `chart.yaml`. [Commit here](https://github.com/broadinstitute/cromwhelm/commit/c2bae2e21214294affe7c4da3216130846f2f212).
- [GitHub workflow run logs](https://github.com/broadinstitute/cromwhelm/runs/6159672103?check_suite_focus=true) for above shows only 2 files changed
Now:
- The [latest GitHub workflow …

[BW-1209] Update auto publish chart workflow to add the newly created package chart 

---

coa-helm/templates/relay-listener-deployment.yaml
coa-helm/values.yaml

Builds off of #31 and depends on https://github.com/DataBiosphere/terra-azure-relay-listeners/pull/17. This enables workspace-based authorization in our app's Listener. 
Currently running in our CaaAoA instance. I confirmed that when I passed my token from Terra dev, I could successfully call `https://terra-coa.servicebus.windows.net/terra-coa-cromwellapp/engine/v1/version`. Without the token, or with a differently configured listener, I got a 403.

BT-565 Enable auth in listener

---

cromwell-helm/templates/batch-analysis-ui-config.yaml
cromwell-helm/templates/batch-analysis-ui.yaml
cromwell-helm/values.yaml

Chart deployed and running in a (manually updated) app instance:

BW-1291: Add UI status element into helm chart

---

cromwell-helm/templates/batch-analysis-ui.yaml
cromwell-helm/templates/cbas-deployment.yaml
terra-batch-libchart/templates/_cbas-api.tpl
terra-batch-libchart/templates/_cbas-ui.tpl

New CBAS Service images:
- DockerHub - [broadinstitute/cbas:0.0.9](https://hub.docker.com/r/broadinstitute/cbas/tags)
- GCR - [us.gcr.io/broad-dsp-gcr-public/cbas:0.0.9](https://console.cloud.google.com/gcr/images/broad-dsp-gcr-public/us/cbas@sha256:1b0afdeb3d0abe2ed50a023144639e3b6901913f3fbe9864441fb72894357bf1/details?project=broad-dsp-gcr-public)
New CBAS UI GCR image: [us.gcr.io/broad-dsp-gcr-public/cbas-ui:0.0.1](https://console.cloud.google.com/gcr/images/broad-dsp-gcr-public/us/cbas-ui@sha256:62bbe55433e2cfb515398e700900a8b1baee304ca46448973270fd1fd1701356/details?project=broad-dsp-gcr-public)
Closes https://broadworkbench.atlassian.net/browse/BW-1296

BW-1296 Update CBAS Service and UI images

---

.github/workflows/update-and-publish-helm-chart.yml

This is kind of a "fake" PR as I have already checked in the most substantive changes... because the test cycle consisted of merging PRs. I have called out the real changed lines below.
https://github.com/broadinstitute/cromwhelm/commit/1af720ab67a32963398a77da2dad562ef988e875 [switch to `broadbot` token]
https://github.com/broadinstitute/cromwhelm/commit/5e87311d087292013b20fc9a87f2baea78062b44 [explicitly check out with `broadbot` as per my [learnings](https://github.com/broadinstitute/cromwell/blob/develop/.github/workflows/chart_update_on_merge.yml#L16-L19) in Cromwell]
https://github.com/broadinstitute/cromwhelm/commit/dcbfe3eb7d55b6e9931acd1df05ce6fb9d639f96 [conditional to stop recursion]

BW-1265 Use `broadbot`

---

.github/workflows/pages.yml

This is 99% a prebuilt template based on the Pages workflow already used under the cover.
The only new lines are
```
if: ( startsWith(github.event.head_commit.message, 'Auto update cromwell-helm chart') )
```

BW-1265 Turn off wasteful Github Pages builds

---

terra-batch-libchart/values.yaml

`c39ee0d` contains CORS fixes that are necessary for the UI to connect.

update WDS image to c39ee0d

---

terra-batch-libchart/values.yaml

Updates WDS image to `f25cf44`, which includes CORS fixes from https://github.com/DataBiosphere/terra-workspace-data-service/pull/94

update WDS image to include CORS fixes [AJ-632]

---

.github/workflows/update-and-publish-helm-chart.yml

It looks like this repo's actions _is_ bumping the `coa-helm` chart version, but not publishing it to GitHub pages. Hoping this does the trick.
We are also not yet auto-updating Leo with `coa-helm` version upgrades, but I'm thinking we can punt that till later as the Azure stuff is still a bit in flux.

TOAZ-243: Also publish Cromwell on Azure to github pages

---

.github/workflows/automerge.yml

this workflow should cause PRs with an "automerge" label (and _without_ a "work in progress" label) to be automatically merged into this repository.
this is really part of an effort to configure this functionality in Leonardo, but we'd like to test it here first (due to lower consequences for failure).
(note that automerged PRs should not trigger other workflows -- in other words, we should not expect to see the Leo PR workflow run as a direct consequence of an automerged PR)
although this is a test, we may find this functionality useful in our repo as well.

[WM-1471] add automerge workflow to Cromwhelm

---

coa-helm/templates/relay-listener-deployment.yaml
coa-helm/values.yaml

Provides helm support for new `samAction` parameter added here: https://github.com/DataBiosphere/terra-azure-relay-listeners/pull/22/
Leo needs to configure the sam action differently depending on whether it's a runtime or kubernetes-app.
Tested this locally using Leo `AKSManualTest`.

TOAZ-242 Add samAction parameter to listener deployment

---

coa-helm/templates/cromwell.yaml
cromwell-helm/templates/cromwell.yaml

Includes workflow start rates pre- https://github.com/broadinstitute/firecloud-develop/pull/2730, since that change was made for distributional, rather than start-rate, reasons.

WM-1526: Increase workflow start rate

---

.github/workflows/update-and-publish-helm-chart.yml

For our future selves: the Jira ID is "AJ-696" because it is related to a discussion between David, Michael, and Chris releasing a new version of WDS to Leonardo through the cromwhelm charts. The newly-implemented automerge functionality in Leonardo requires that a Jira ID representing the change is present in the commit message.

[AJ-696] remove check against auto-updates

---

coa-helm/templates/cbas-api.yaml
coa-helm/templates/cbas-ui.yaml
coa-helm/templates/cromwell.yaml
coa-helm/templates/wds.yaml

Error:
```
The command 'helm installChart' failed with result unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment): unknown field "Error" in io.k8s.api.apps.v1.Deployment"
```
This seems to fix it, I wish I had a better understanding as to why. All `nindent` does compared to `indent` is prepend a newline. Maybe a consequence of the yaml merge logic in https://github.com/broadinstitute/cromwhelm/blob/main/terra-batch-libchart/templates/_util.yaml? I do notice that the libchart uses `nindent` ([example](https://github.com/broadinstitute/cromwhelm/blob/main/terra-batch-libchart/templates/_cbas-ui.tpl#L16)).
There is an error in templating, and the `aadpodidbinding`, `leoAppName`, `workspaceId` pod labels are nowhere …

[AJ-676 follow up] Use nindent instead of indent to avoid yaml merge issues

---

coa-helm/templates/tes.yaml

This PR temporarily disables TES -- since TES is not functional yet, this removes any problems that TES might cause within an AKS cluster
Eventually, TES will be re-integrated though

Temporarily disable TES Deployment in coa-helm chart

---

coa-helm/templates/tes.yaml

Trivial change from https://github.com/broadinstitute/cromwhelm/pull/168 in order to invoke Github Actions correctly (needs a JIRA ticket ID in name)
This PR temporarily disables TES -- since TES is not functional yet, this removes any problems that TES might cause within an AKS cluster
Eventually, TES will be re-integrated though

AJ-717: Temporarily disable TES Deployment in coa-helm chart

---

terra-batch-libchart/templates/_reverse-proxy.tpl

Default setting for `client_max_body_size` in nginx is 1M, apparently.
This restricts the size of TSV uploads for WDS. In this PR, I increase that limit to 50M.
We may want to pipe this through values at some point instead of hardcoding it?

AJ-827: increase client body size to 50M for WDS

---

coa-helm/Chart.yaml
coa-helm/templates/cromwell.yaml
terra-batch-libchart/templates/_cbas-api.tpl
terra-batch-libchart/templates/_wds.tpl

See [AJ-822](https://broadworkbench.atlassian.net/browse/AJ-822)
Add initial requests and limits for CPU and memory for the CBAS, Cromwell, and WDS containers.  I welcome comments and suggestions on what are sensible numbers to use.  In most cases I've seen the numbers I have here are extremely conservative - most cpu values I've seen for containers are <~100m, memory <~256Mi - but I have seen containers that leap up to 600m+ cpu and 600Mi+ memory - unclear if we can expect those values to be necessary in normal usage or if something pathological was happening.
[AJ-822]: https://broadworkbench.atlassian.net/browse/AJ-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-822 add resource limits

---

terra-batch-libchart/values.yaml

updating a comment; the previous PR merge didn't trigger the actions that auto-bump the chart.

AJ-836: update comment

---

cromwell-helm/templates/ingress.yaml

Relevant context can be found here: https://broadinstitute.slack.com/archives/C1EH66VCM/p1675346412119639
But the TL;DR is that the `networking.k8s.io/v1beta1` has been deprecated after k8s 1.21 and needs to be updated.

[IA-3656] update deprecated k8 networking api version to v1

---

cromwell-helm/templates/ingress.yaml

Turns out that there was a few breaking changes when moving from the v1beta to the V1 endpoint:
https://github.com/kubernetes/kubernetes/pull/89778
The pathType cannot be defaulted anymore, it looks like `Prefix` would be the correct option - https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
JIRA ticket: https://broadworkbench.atlassian.net/browse/IA-4021

[IA-4021] fix the ingress path syntax for new v1 endpoint

---

cromwell-helm/values.yaml

Haven't tested yet, will test through Leo.
See https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/928
This PV _should_ be read-write as it supports postgres and is mapped 1-1 with a user-owned persistent disk. A theory is this setting was always incorrect, but just started to fail in the GKE 1.24 upgrade.

Change persistent volume accessMode to ReadWriteOnce for cromwell-gcp

---

terra-batch-libchart/templates/_reverse-proxy.tpl

All requests through the proxy will now generate access logs along the lines of:
```
10.244.11.17 - - [15/Feb/2023:15:02:56 +0000] "GET /cbas/api/batch/v1/methods?method_id=00000000-0000-0000-0000-000000000008 HTTP/1.1" 200 616 "https://lzf07312d05014dcfc2a6d8244c0f9b166a3801f44ec2b003d.servicebus.windows.net/wds-410a5a2e-d1dd-4327-add4-73e0e6248938/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
10.244.11.17 - - [15/Feb/2023:15:04:59 +0000] "GET /cbas/status HTTP/1.1" 200 64 "-" "http4s-blaze/1.0.0-M35"
10.244.11.17 - - [15/Feb/2023:15:11:36 +0000] "GET /cbas/status HTTP/1.1" 200 64 "-" "http4s-blaze/1.0.0-M35"
```

WM-1681: Access log for requests through proxy

---

cromwell-helm/Chart.yaml

This value was no longer used anywhere. Confirmed that I can still `helm template cromwell-helm` without it.
See also https://github.com/broadinstitute/cromwell/pull/7014

WX-952 Remove obsolete Cromwell version

---

cromwell-helm/templates/cromwell.yaml

AoU needs to enable call caching and it is must have for AoU launching CaaA for GCP. 
I see we already create a postgres DB in that cluster for Cromwell, seems this is the only thing left.

[RW-8626] Enable Cromwell call caching for CaaA on GCP

---

terra-batch-libchart/templates/_wds.tpl

Relates to https://broadworkbench.atlassian.net/browse/AJ-764
Need to use `APPLICATIONINSIGHTS_CONNECTION_STRING` per docs here https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=java

AJ-764: Use appropriate env var naming per Azure docs

---

coa-helm/README.md

updating the README; the previous PR merge didn't trigger the actions that auto-bump the chart.

AJ-764: update README

---

coa-helm/templates/cromwell.yaml

Support for this new config added in https://github.com/broadinstitute/cromwell/pull/7122

WX-990 Configure request backoff behavior for Cromwell TES backend

---

terra-batch-libchart/templates/_cbas-api.tpl

To avoid CBAS pods looking healthy when the app is unresponsive

WM-1986: Liveness polling for CBAS

---

coa-helm/templates/cromwell.yaml

This silences a warning Akka has been printing and is consistent with how we run Cromwell in other contexts.

WX-987 Use modern Akka http connection pool

---

cromwell-helm/templates/cromwell.yaml

With VPC turned on, `noAddress` has to be `true`, otherwise we'll get the following error
```
"message": "Unable to complete Batch request due to a problem with the request (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: no_external_ip_address field is invalid. VPC Service Controls is enabled for the project, so external ip address must be disabled for the job. Please set no_external_ip_address field to be true). "
```

RW-14545 Set `noAddress` as default

---

cromwell-helm/Chart.yaml
terra-batch-libchart/values.yaml

As of https://github.com/broadinstitute/cromwell/pull/7734 the `Latest` for cromwell images follows the numerical community releases (rather than develop)
This PR sets the cromwell app to follow these stable releases

[AN-514] Have Cromwell App follow the `latest` tag
